### ISSUE TITLE
Scope cannot be set on the AuthenticationAPIClient passed to GoogleAuthProvider

### ISSUE THREAD

**Issue by Neeraj-IOH** [auth0/Lock-Google.Android#28]
There is no way to change the scope of AuthenticationAPIClient when using it with GoogleAuthProvider. please provide a functionality to do the same.

**Comment by lbalmaceda** [comment]
Hello @Neeraj-IOH. Thanks for the heads up.
The `AuthProvider` class in one of the latest versions of `auth0.android` library has the setter/getter for the authentication parameters. I have submited a PR and will wait until we release a new version of both `auth0.android` and `lock.android` before merging it. 
If you are in a rush, check the changes here https://github.com/auth0/Lock-Google.Android/pull/29. Note that if you're using it with lock you'll have to wait for the next release.

Cheers.
