### ISSUE TITLE
Docs: Refresh Token

### ISSUE THREAD

**Issue by ritdaw** [auth0/Lock-Google.Android#30]
Is there any documentation on how to set the scope to "openid offline_access" to gain access to the refresh token?

**Comment by lbalmaceda** [comment]
Hi @ritdaw,
In your case, you should specify both the `scope` and the `device` keys as additional authentication parameters, but this is still not merged and will be resolved on the next release. Check the PR changes if you need them right away.

Related issue https://github.com/auth0/Lock-Google.Android/issues/28 
Cheers.

**Comment by ritdaw** [comment]
Any idea when you will be releasing?
