### ISSUE TITLE
Missing required parameter: response_type error

### ISSUE THREAD

**Issue by BrianAdams** [auth0/Lock-Google.Android#34]
I have been using the standard native lock for Android (version 2.5.0) with Google authentication a while now.  I am attempting to add the Lock-Google.Android extension (version 1.1.0 ) for the native support.  I have run through the install configuration 4 times and verified everything is per the documentation save one thing: that inside google's developer console, my "web clients" (which is the one configured in the Social>Connection>Google configuration) and my "native client" are in different projects under the same organization.  I have native clients, web clients, etc, that are all using the same accounts in Auth0 which only has  a single Social setting per provider, so this does not seem like an odd configuration.

On the Auth0 logs I see the following log message when attempting to authenticate:
```
{
  "date": "2017-05-23T21:38:05.415Z",
  "type": "f",
  "description": "Missing required parameter: response_type",
  "connection_id": "",
  "ip": "XX.XX.XX.XX",
  "user_agent": "Android",
  "details": {
    "body": {},
    "qs": {},
    "error": {
      "message": "Missing required parameter: response_type",
      "oauthError": "invalid_request",
      "type": "request-error"
    }
  },
  "log_id": "49560429270835143462031386526893258363066610327733927938"
}
```
On the Android side I get the following error message in the Android logs (but not in the application logs, nor do the auth failed event handlers fire):
```
You have wrong OAuth2 related configurations, please check. Detailed error: INVALID_AUDIENCE
```
The standard Lock with webpage redirects work fine when I remove the Lock-Google provider from the android code.

All I have found so far is a unqualified reference that there may be a requirement that both clients in the google console have to exist in the same project (https://stackoverflow.com/questions/15031238/google-api-and-android-oauth-invalid-audience-error).

Do you know if that is indeed a requirement?  Any other suggestion on what I might check?

**Comment by lbalmaceda** [comment]
You said you have separate projects in the _Google Dev Console_ for the web and the native clients. IMO projects are like applications and if they share APIs they should all be under the same project. Have you tried to reproduce this with a single project with both clients? If you had and it worked then I'm afraid it's an external limitation.
